## Build Training set for doc types

In [2]:
import TWB
import glob

In [3]:
import pandas as pd
import nltk
from nltk.stem import PorterStemmer
#from nltk.stem import LancasterStemmer
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'\w+')
porter = PorterStemmer()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/sparaschiakos/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
english_document_data = pd.read_pickle('data/english_document_data.pkl')
stems = pd.read_pickle('data/stemmed_data.pkl')
freq_content = pd.read_pickle('data/freq_content.pkl')

In [48]:
stems.shape

(34525, 2)

In [4]:
# # defining function to check buzz word 
# def exist_(temp,j): 
#     temp2=temp.lower()
#     temp3=temp2.find(j)
#     return temp3>0
    
# dictionary2=['certificate','instruction','poster','protocol', 'presentation',
#              'response','letter','report','map','manual','banner']

# for j in dictionary2:
#     jj=english_document_data.Filename.apply(lambda x: exist_(x,j))
#     rr=pd.DataFrame(columns=[str(j)])
#     rr[str(j)]=jj
#     english_document_data=pd.concat([english_document_data,rr ], axis=1)

In [5]:
# keep only the english ones
stems_en = stems.iloc[english_document_data.index]
freq_content_en = freq_content.iloc[english_document_data.index]

In [6]:
# drop dublicates and create the corpus
stems_en_noDbl = stems_en.drop_duplicates(subset='Content')
len(stems_en_noDbl.index)

6730

In [277]:
# drop duplicates of english_document_data based on content 
english_document_data_noDbl = english_document_data.loc[stems_en_noDbl.index]

In [278]:
# keep df with true in labels
df = english_document_data_noDbl.loc[
    (english_document_data_noDbl['certificate']==True) |
    (english_document_data_noDbl['instruction']==True) |
    (english_document_data_noDbl['poster']==True) |
    (english_document_data_noDbl['protocol']==True) |
    (english_document_data_noDbl['presentation']==True) |
    (english_document_data_noDbl['response']==True) |
    (english_document_data_noDbl['letter']==True) |
    (english_document_data_noDbl['report']==True) |
    (english_document_data_noDbl['map']==True) |
    (english_document_data_noDbl['manual']==True) |
    (english_document_data_noDbl['banner']==True)]

In [279]:
labeled_docs = pd.DataFrame(index= df.index, columns=['document', 'label'])

In [280]:
# keep docs with label
for i in df.index:
    go = False
    for j in df.columns:
        if (df[j][i] == True) & (go == False):
            labeled_docs.document[i] = df.Filename[i]
            labeled_docs.label[i] = j
            go = True

In [281]:
labeled_docs

document         label
205       English_Volunteer_Newsletter_January_2017.docx        letter
461    201702_Letter_from_the_NGO_Committee_on_Migrat...        letter
692               Labels_for_Emergency_Response_Map.docx      response
1064          CP_protocol_FINAL_with_LSTMH_approval.docx      protocol
1191   2a_Data_and_information_for_epidemic_response_...      response
1193   2b_Laboratory_networks_to_support_outbreak_pre...      response
1195                    Publisher_report_2016_final.docx        report
1202     CAFE_newsletter_Apr_2017_for_translation_1.docx        letter
1206     CAFE_newsletter_Apr_2017_for_translation_2.docx        letter
1419                  BRONZE_Annual_Report_Template.docx        report
1423               SILVER_Annual_Report_Template(1).docx        report
1440   CDS_Rehab_completion_report_-for_translation_i...        report
1441   CDS_Rehab_completion_report_-for_translation_i...        report
1485   Disability_Inclusion_and_Etiquette_Training_pr...  presentation
1599   5._Module_1_-_Worldmap_Camps_and_camp-like_set...           map
1748   Denmark_funds_emergency_response_for_the_recen...      response
1751   Denmark_funds_emergency_response_for_South_Sud...      response
1754   CESCR_-_report_on_France_ETOs_and_private_educ...        report
1755   Latvia_supports_UNHCR’s_regional_response_to_t...      response
1808   Updated_Amendment_Training_Powerpoint_Presenta...  presentation
1834   Sweden_Supports_the_Emergency_Response_in_Iraq...      response
1916                  RUTF_Description_and_Protocol.docx      protocol
2322            Final_Report_Shamwana_December_2016.docx        report
2486           FWM_Training_Certificate-_BrandedWORD.doc   certificate
2553     TdH_Child_Labour_Report_2017_-_FINAL_short.docx        report
2677                  May_2017_Volunteer_Newsletter.docx        letter
2762   Higher_Education_For_Refugees__Welcome_Map__EN...           map
3027   WABA_files_for_translation.zip___SEP___2017_WB...        poster
3086         CAFE_Follow-up_Letter_to_RFU_June_17_v2.doc        letter
3211                     June-Volunteer_Newsletter_.docx        letter
...                                                  ...           ...
32550    CARE_Idai_Certificate_of_Donation_-Schools.docx   certificate
32577  AAP_Posters.zip___SEP___AAP_Posters_(00000002)...        poster
32581  AAP_Posters.zip___SEP___AAP_Posters_(00000002)...        poster
32585  AAP_Posters.zip___SEP___AAP_Posters_(00000002)...        poster
32589  AAP_Posters.zip___SEP___AAP_Posters_(00000002)...        poster
32593  AAP_Posters.zip___SEP___AAP_Posters_(00000002)...        poster
32639               April_2019_Volunteer_Newsletter.docx        letter
32852  1_Modulo_Core.zip___SEP___NC_RCRCMod_VOLMANUAL...        manual
32862                       NC_Assessment_VOLMANUAL.docx        manual
32937                               NC_BC_VOLMANUAL.docx        manual
33131  Module_7.zip___SEP___MNCH_VolManual_Complete.docx        manual
33187                                5.1_Fin_Report.docx        report
33357       Module_8.zip___SEP___NC_MHPSS_VOLMANUAL.docx        manual
33592  Mod_11_and_12.zip___SEP___VNRBD_VolManual_Comp...        manual
33704  UN_Refugee_Chief_urges_Security_Council_for_fi...      response
33716               Conference_Report_Website_Story.docx        report
33738                 2018_HEART_Faciltiator_Manual.docx        manual
33798                               Tobacco_posters.docx        poster
33817   Forms.zip___SEP___TE_Letter_to_Parents_2019.docx        letter
33832           19-_Abdallah_Beirakdar-_Bekaa-_MAPS.docx           map
33856                            Tobacco_posters_MY.docx        poster
34013         tot_training_manual_copy_2_-_pp_40-44.docx        manual
34116               Manual_w_out_drill_instructions.docx   instruction
34229                   5.C._Case_Conference_Report.docx        report
34243                   3.B._Case_Conference_Report.docx        report
3

## Compute the relative freqs per word in the corpus per document

In [ ]:
# create the list with all the contents
texts =[]
texts = list(stems_en_noDbl.Content)
token_freq = [ TWB.common.freq(t.split(' ')) for t in texts ]
token_freq[0]

In [59]:
dictionary = list(set(' '.join(texts).split(' ')))
dict_idx = { w : i for (i,w) in enumerate(dictionary) }
# dict_idx

In [60]:
import numpy as np
M = np.zeros((len(texts),len(dictionary)))

In [63]:
for i, text in enumerate(texts):
    M[i,[dict_idx[w] for w in token_freq[i].keys()]] = np.array(list(token_freq[i].values()))/sum(token_freq[i].values())

In [197]:
# the relative freqs per word per document
labeled_set= pd.DataFrame(M, columns=dictionary,index=stems_en_noDbl.index)

In [161]:
labeled_set

prosynergi  hangout  sodi  sindhuli  aprenden  sgsa  \
0      0.005747         0.0      0.0   0.0       0.0       0.0   0.0   
7      0.005155         0.0      0.0   0.0       0.0       0.0   0.0   
13     0.005650         0.0      0.0   0.0       0.0       0.0   0.0   
16     0.007042         0.0      0.0   0.0       0.0       0.0   0.0   
19     0.000034         0.0      0.0   0.0       0.0       0.0   0.0   
22     0.000114         0.0      0.0   0.0       0.0       0.0   0.0   
29     0.001580         0.0      0.0   0.0       0.0       0.0   0.0   
30     0.000530         0.0      0.0   0.0       0.0       0.0   0.0   
106    0.000223         0.0      0.0   0.0       0.0       0.0   0.0   
107    0.002481         0.0      0.0   0.0       0.0       0.0   0.0   
116    0.001437         0.0      0.0   0.0       0.0       0.0   0.0   
120    0.001812         0.0      0.0   0.0       0.0       0.0   0.0   
132    0.001901         0.0      0.0   0.0       0.0       0.0   0.0   
144    0.001934         0.0      0.0   0.0       0.0       0.0   0.0   
156    0.002320         0.0      0.0   0.0       0.0       0.0   0.0   
168    0.002273         0.0      0.0   0.0       0.0       0.0   0.0   
181    0.009434         0.0      0.0   0.0       0.0       0.0   0.0   
188    0.004545         0.0      0.0   0.0       0.0       0.0   0.0   
197    0.004274         0.0      0.0   0.0       0.0       0.0   0.0   
205    0.000637         0.0      0.0   0.0       0.0       0.0   0.0   
220    0.000124         0.0      0.0   0.0       0.0       0.0   0.0   
221    0.003012         0.0      0.0   0.0       0.0       0.0   0.0   
228    0.006944         0.0      0.0   0.0       0.0       0.0   0.0   
232    0.003356         0.0      0.0   0.0       0.0       0.0   0.0   
246    0.002506         0.0      0.0   0.0       0.0       0.0   0.0   
270    0.004975         0.0      0.0   0.0       0.0       0.0   0.0   
294    0.002445         0.0      0.0   0.0       0.0       0.0   0.0   
318    0.002132         0.0      0.0   0.0       0.0       0.0   0.0   
326    0.003344         0.0      0.0   0.0       0.0       0.0   0.0   
350    0.002053         0.0      0.0   0.0       0.0       0.0   0.0   
...         ...         ...      ...   ...       ...       ...   ...   
34323  0.001381         0.0      0.0   0.0       0.0       0.0   0.0   
34327  0.002882         0.0      0.0   0.0       0.0       0.0   0.0   
34332  0.005348         0.0      0.0   0.0       0.0       0.0   0.0   
34334  0.002016         0.0      0.0   0.0       0.0       0.0   0.0   
34335  0.000044         0.0      0.0   0.0       0.0       0.0   0.0   
34353  0.000070         0.0      0.0   0.0       0.0       0.0   0.0   
34368  0.000126         0.0      0.0   0.0       0.0       0.0   0.0   
34376  0.004115         0.0      0.0   0.0       0.0       0.0   0.0   
34377  0.000035         0.0      0.0   0.0       0.0       0.0   0.0   
34378  0.000070         0.0      0.0   0.0       0.0       0.0   0.0   
34393  0.000044         0.0      0.0   0.0       0.0       0.0   0.0   
34408  0.001355         0.0      0.0   0.0       0.0       0.0   0.0   
34409  0.001122         0.0      0.0   0.0       0.0       0.0   0.0   
34410  0.001025         0.0      0.0   0.0       0.0       0.0   0.0   
34411  0.021739         0.0      0.0   0.0       0.0       0.0   0.0   
34412  0.003215         0.0      0.0   0.0       0.0       0.0   0.0   
34413  0.002137         0.0      0.0   0.0       0.0       0.0   0.0   
34414  0.002110         0.0      0.0   0.0       0.0       0.0   0.0   
34415  0.002193         0.0      0.0   0.0       0.0       0.0   0.0   
34416  0.009091         0.0      0.0   0.0       0.0       0.0   0.0   
34419  0.000643         0.0      0.0   0.0       0.0       0.0   0.0   
34423  0.000135         0.0      0.0   0.0       0.0       0.0   0.0   
34453  0.047619         0.0      0.0   0.0       0.0       0.0   0.0   
34462  0.000805         0.0      0.0   0.0       0.0     

In [67]:
# keep cols with only digits
digit_stems = []
for col in labeled_set.columns:
    if col.isdigit():
        digit_stems.append(col)  
len(digit_stems)

In [199]:
# compute and keep the amount of digit stems per doc
labeled_set['__digits'] = labeled_set[digit_stems].apply(sum,axis=1)

In [200]:
# drop digit columns
labeled_set = labeled_set.drop(columns=digit_stems)

In [282]:
# create a column for the labels for all the docs and impute as unknown
labeled_set["label"] = 'Unknown'

In [283]:
# impute the knwon labels
for i in labeled_docs.index:
        labeled_set['label'].loc[i] = labeled_docs["label"].loc[i]

In [284]:
labeled_docs['label'].unique()

array(['letter', 'response', 'protocol', 'report', 'presentation', 'map',
       'certificate', 'poster', 'manual', 'instruction'], dtype=object)

In [285]:
# merge instructions and manual
labeled_docs['label'].loc[(labeled_docs['label']=='manual') | 
                          (labeled_docs['label']=='instruction')] = 'manual/instruction'

In [286]:
# save the labeled set of docs 
labeled_set.to_pickle('data/labeled_set_type.pkl')

## PCA

In [5]:
from sklearn.datasets import fetch_mldata
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.model_selection import train_test_split
import pandas as pd

In [7]:
# load labeled_set
labeled_set = pd.read_pickle('data/labeled_set_type.pkl')

In [8]:
# keep only features
features_doc_types = labeled_set.drop(columns=['label'])

In [9]:
# standarize
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit on training set only.
scaler.fit(features_doc_types)
# Apply transform to both the training set and the test set.
train_img = scaler.transform(features_doc_types)

In [10]:
from sklearn.decomposition import PCA
pca = PCA(.95)

In [11]:
pca.fit(train_img)

PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
import joblib
print(pca.n_components_)

joblib.dump(pca,'docClassif/pca_type.pkl')

## Training Classifiers

In [192]:
from pandas.tools.plotting import parallel_coordinates
import pandas as pd
from sklearn import svm

from sklearn.metrics import jaccard_similarity_score

#from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

random_state = 100
#import xgboost as xgb

import pickle
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np
from sklearn.model_selection import cross_val_score

In [193]:
pca.n_components_

3685

In [288]:
# keep all the docs with label (drop unknown)
features_to_class = features_doc_types.loc[labeled_docs.index]
test_to_class = labeled_set.label.loc[labeled_docs.index]

In [289]:
features_to_class

prosynergi  hangout  sodi  sindhuli  aprenden  sgsa  \
205    0.000637         0.0      0.0   0.0       0.0       0.0   0.0   
461    0.003788         0.0      0.0   0.0       0.0       0.0   0.0   
692    0.024390         0.0      0.0   0.0       0.0       0.0   0.0   
1064   0.000267         0.0      0.0   0.0       0.0       0.0   0.0   
1191   0.001585         0.0      0.0   0.0       0.0       0.0   0.0   
1193   0.001181         0.0      0.0   0.0       0.0       0.0   0.0   
1195   0.000389         0.0      0.0   0.0       0.0       0.0   0.0   
1202   0.001479         0.0      0.0   0.0       0.0       0.0   0.0   
1206   0.002381         0.0      0.0   0.0       0.0       0.0   0.0   
1419   0.001748         0.0      0.0   0.0       0.0       0.0   0.0   
1423   0.001416         0.0      0.0   0.0       0.0       0.0   0.0   
1440   0.000434         0.0      0.0   0.0       0.0       0.0   0.0   
1441   0.000454         0.0      0.0   0.0       0.0       0.0   0.0   
1485   0.002778         0.0      0.0   0.0       0.0       0.0   0.0   
1599   0.001600         0.0      0.0   0.0       0.0       0.0   0.0   
1748   0.002020         0.0      0.0   0.0       0.0       0.0   0.0   
1751   0.002179         0.0      0.0   0.0       0.0       0.0   0.0   
1754   0.000081         0.0      0.0   0.0       0.0       0.0   0.0   
1755   0.002755         0.0      0.0   0.0       0.0       0.0   0.0   
1808   0.001181         0.0      0.0   0.0       0.0       0.0   0.0   
1834   0.002494         0.0      0.0   0.0       0.0       0.0   0.0   
1916   0.000879         0.0      0.0   0.0       0.0       0.0   0.0   
2322   0.000155         0.0      0.0   0.0       0.0       0.0   0.0   
2486   0.041667         0.0      0.0   0.0       0.0       0.0   0.0   
2553   0.000408         0.0      0.0   0.0       0.0       0.0   0.0   
2677   0.000637         0.0      0.0   0.0       0.0       0.0   0.0   
2762   0.015625         0.0      0.0   0.0       0.0       0.0   0.0   
3027   0.003401         0.0      0.0   0.0       0.0       0.0   0.0   
3086   0.002033         0.0      0.0   0.0       0.0       0.0   0.0   
3211   0.000749         0.0      0.0   0.0       0.0       0.0   0.0   
...         ...         ...      ...   ...       ...       ...   ...   
32550  0.008772         0.0      0.0   0.0       0.0       0.0   0.0   
32577  0.007519         0.0      0.0   0.0       0.0       0.0   0.0   
32581  0.007874         0.0      0.0   0.0       0.0       0.0   0.0   
32585  0.007874         0.0      0.0   0.0       0.0       0.0   0.0   
32589  0.007407         0.0      0.0   0.0       0.0       0.0   0.0   
32593  0.007407         0.0      0.0   0.0       0.0       0.0   0.0   
32639  0.000543         0.0      0.0   0.0       0.0       0.0   0.0   
32852  0.000191         0.0      0.0   0.0       0.0       0.0   0.0   
32862  0.000061         0.0      0.0   0.0       0.0       0.0   0.0   
32937  0.000225         0.0      0.0   0.0       0.0       0.0   0.0   
33131  0.000087         0.0      0.0   0.0       0.0       0.0   0.0   
33187  0.030303         0.0      0.0   0.0       0.0       0.0   0.0   
33357  0.000100         0.0      0.0   0.0       0.0       0.0   0.0   
33592  0.000251         0.0      0.0   0.0       0.0       0.0   0.0   
33704  0.001869         0.0      0.0   0.0       0.0       0.0   0.0   
33716  0.003401         0.0      0.0   0.0       0.0       0.0   0.0   
33738  0.000068         0.0      0.0   0.0       0.0       0.0   0.0   
33798  0.038462         0.0      0.0   0.0       0.0       0.0   0.0   
33817  0.003559         0.0      0.0   0.0       0.0       0.0   0.0   
33832  0.004587         0.0      0.0   0.0       0.0       0.0   0.0   
33856  0.029412         0.0      0.0   0.0       0.0       0.0   0.0   
34013  0.000878         0.0      0.0   0.0       0.0       0.0   0.0   
34116  0.000290         0.0      0.0   0.0       0.0       0.0   0.0   
34229  0.001267         0.0      0.0   0.0       0.0     

In [290]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(features_to_class, test_to_class, test_size=0.3)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)


(397, 107251) (397,)
(171, 107251) (171,)


In [298]:
type(X_train)

numpy.ndarray

In [292]:
# transform features from PCA
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)

In [299]:
pd.DataFrame(X_train).to_pickle('X_train_docType.pkl')
pd.DataFrame(X_test).to_pickle('X_test_docType.pkl')

In [ ]:
pd.DataFrame(Y_train).to_pickle('Y_train_docType.pkl')
pd.DataFrame(Y_test).to_pickle('Y_test_docType.pkl')

### Random Forest

In [209]:
# Hyperparameter Optimization for random forest
from scipy.stats import randint as sp_randint

from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, make_scorer
from time import time
# initialize the classifier
clf_RF = RandomForestClassifier(n_estimators=10, n_jobs=-1, random_state=100)
# find the number of features for parameter optimization
num_features = train_img.shape[1]

# make scorer#
#auc_scorer = make_scorer(roc_auc_score, needs_threshold=True)#, needs_proba=True

# params
m_depths = [None] + list(range(2, 21, 3))
# specify parameters and distributions to sample from
param_dist_rf = {"max_depth": m_depths, # [None, 2, 5, 8, 11, 14, 17, 20]
                 "max_features": sp_randint(1, num_features),
                 "min_samples_split": sp_randint(2, 100),
                 "min_samples_leaf": sp_randint(1, 100),
                 "bootstrap": [True, False],
                 "criterion": ["gini", "entropy"]}

n_iter_search = 30 # was 20

# run randomized search
random_search_RF = RandomizedSearchCV(clf_RF, 
                                      param_distributions=param_dist_rf,
                                      n_iter=n_iter_search,
                                      random_state=random_state,
                                      n_jobs=-1,
                                      return_train_score=True)

start = time()
random_search_RF.fit(X_train, Y_train)
print("RandomizedSearchCV took {:.2f} seconds for {} candidates"
      " parameter settings.\n".format((time() - start), n_iter_search))

# display the dataframe without the parameters column for better rendering
display(pd.DataFrame(random_search_RF.cv_results_).drop('params', axis=1))

best_parameters_RF = pd.Series(random_search_RF.best_params_)

# display the best set of parameters
display(best_parameters_RF)

RandomizedSearchCV took 1405.56 seconds for 30 candidates parameter settings.



mean_fit_time  mean_score_time  mean_test_score  mean_train_score  \
0       31.223052         5.670263         0.919125          0.919127   
1       13.210189         3.622221         0.919125          0.919127   
2       15.783922         3.268891         0.919125          0.919127   
3        9.070457         2.349524         0.919125          0.919127   
4       12.246951         2.491501         0.919125          0.919127   
5        7.845189         1.305541         0.918913          0.920717   
6       13.609464         3.354864         0.919125          0.919127   
7       15.612455         3.010050         0.919125          0.919127   
8       11.108730         2.359816         0.919125          0.919127   
9       15.249608         3.295619         0.919125          0.919127   
10      12.123177         2.350166         0.919125          0.919127   
11      15.207909         1.914132         0.919125          0.919127   
12      10.914526         2.534285         0.919125          0.919127   
13      11.609987         1.565092         0.919125          0.919127   
14      12.766165         1.958270         0.919125          0.919127   
15       8.531482         2.298338         0.919125          0.919127   
16      11.410287         2.659263         0.919125          0.919127   
17      48.229628         4.856741         0.919125          0.919127   
18      73.524271         7.606134         0.919125          0.919127   
19      58.113571         2.943191         0.919125          0.919127   
20      78.899716         3.403223         0.919125          0.919127   
21      44.452917         2.476916         0.919125          0.919127   
22      44.961162         2.742307         0.919125          0.919127   
23      42.300217         2.302030         0.919125          0.919127   
24      42.900693         2.309686         0.919125          0.919127   
25      40.602988         2.282140         0.919125          0.919127   
26      41.798121         2.673415         0.919125          0.919127   
27      42.279698         2.375242         0.919125          0.919127   
28      39.551018         2.410813         0.919125          0.919127   
29      31.416741         1.704285         0.918913          0.919975   

   param_bootstrap param_criterion param_max_depth param_max_features  \
0             True            gini               8                 80   
1             True            gini               5                 54   
2             True         entropy            None                281   
3             True            gini               8               1674   
4             True         entropy              11               1925   
5            False         entropy               8                613   
6            False         entropy              20               2098   
7            False            gini              20               3016   
8            False         entropy              17               1428   
9            False         entropy            None               3311   
10           False         entropy              14                807   
11            True            gini               5                438   
12            True         entropy               5               3103   
13            True            gini            None               3420   
14           False            gini            None                 14   
15            True         entropy              17               1668   
16            True         entropy              17                496   
17           False            gini              11               1836   
18           False            gini              17               1119   
19            True         entropy               5               1101   
20            True            gini              17               3329   
21           False            gini              17                819   
22           False         entropy               2           

bootstrap            True
criterion            gini
max_depth               8
max_features           80
min_samples_leaf       49
min_samples_split      12
dtype: object

In [293]:
# Train optimized random forest
model7 = RandomForestClassifier(n_estimators=10 ,
                                min_samples_split= 12,
                                min_samples_leaf=49,
                                bootstrap = True,
                                criterion = 'gini',
                                max_depth = 8,
                                max_features = 80,
                                n_jobs=-1,
                                random_state=100)

model7.fit(X_train, Y_train)
print('train accuracy: '+str(jaccard_similarity_score(model7.predict(X_train), Y_train)))
print('test accuracy: '+str(jaccard_similarity_score(model7.predict(X_test), Y_test)))


train accuracy: 0.5340050377833753
test accuracy: 0.5730994152046783


In [266]:
X_train

prosynergi  hangout  sodi  sindhuli  aprenden  sgsa  \
6466        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
4209        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
12128       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
9567        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
31637       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
16998       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
6477        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
33775       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
215         NaN         NaN      NaN   NaN       NaN       NaN   NaN   
1926        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
25346       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
29740       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
9825        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
25358       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
24109  0.000379         0.0      0.0   0.0       0.0       0.0   0.0   
19934       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
25342       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
12155       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
4840        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
11994       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
21256       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
9716   0.005747         0.0      0.0   0.0       0.0       0.0   0.0   
14811  0.000583         0.0      0.0   0.0       0.0       0.0   0.0   
21161       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
33594       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
25571       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
31968       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
34275       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
5485   0.062500         0.0      0.0   0.0       0.0       0.0   0.0   
23018       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
...         ...         ...      ...   ...       ...       ...   ...   
11646       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
22651       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
6491        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
6419        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
29946       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
19704  0.002625         0.0      0.0   0.0       0.0       0.0   0.0   
5001        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
32160       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
22663  0.005917         0.0      0.0   0.0       0.0       0.0   0.0   
18682  0.001727         0.0      0.0   0.0       0.0       0.0   0.0   
31746       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
14966  0.000333         0.0      0.0   0.0       0.0       0.0   0.0   
25633  0.000912         0.0      0.0   0.0       0.0       0.0   0.0   
11968       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
31607  0.000937         0.0      0.0   0.0       0.0       0.0   0.0   
11332       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
5337        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
31249       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
21196       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
2491        NaN         NaN      NaN   NaN       NaN       NaN   NaN   
14015       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
10778       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
15733       NaN         NaN      NaN   NaN       NaN       NaN   NaN   
30092       NaN         NaN      NaN   NaN       NaN     

In [294]:
from sklearn.metrics import confusion_matrix
# Compute confusion matrix train
y_true = Y_train
y_pred = model7.predict(X_train)
cm = confusion_matrix(y_true, y_pred)
print(cm)
# Compute confusion matrix train
y_true = Y_test
y_pred = model7.predict(X_test)
cm = confusion_matrix(y_true, y_pred)
print(cm)

[[  0   0   2   0   0   0   0   0   7   0]
 [  0   0   2   0   0   0   0   0   3   0]
 [  0   0  41   0   0   0   0   0  19   0]
 [  0   0   6   0   0   0   0   0  23   0]
 [  0   0   2   0   0   0   0   0  14   0]
 [  0   0   5   0   0   0   0   0  17   0]
 [  0   0   2   0   0   0   2   0  35   0]
 [  0   0   0   0   0   0   1   0  10   0]
 [  0   0   5   0   0   0   0   0 169   0]
 [  0   0   2   0   0   0   0   0  30   0]]
[[ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  3  0]
 [ 0  0 21  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  1  0  8  0]
 [ 0  0  1  0  0  0  0  0  6  0]
 [ 0  0  1  0  0  0  0  0  4  0]
 [ 0  0  1  0  0  0  1  0 12  0]
 [ 0  0  0  0  0  0  0  0  6  0]
 [ 0  0  3  0  0  0  0  0 76  0]
 [ 0  0  1  0  0  0  0  0 10  0]]


In [296]:
count = Y_test.value_counts() 
count

report          79
letter          35
presentation    14
response        11
manual           9
map              7
protocol         6
poster           5
instruction      3
certificate      2
Name: label, dtype: int64